modulomonitoresmonitores:
    resource: "@modulomonitoresmonitoresBundle/Resources/config/routing.yml"
    prefix:   /

moduloclientescliente:
    resource: "@moduloclientesclienteBundle/Resources/config/routing.yml"
    prefix:   /

CriveroPrueba:
    resource: "@CriveroPruebaBundle/Resources/config/routing.yml"
    prefix: /
